### ISSUE TITLE
Plugin always tries to use the aws profile "default"

### ISSUE THREAD

**Issue by mikkilevon** [rogersgt/serverless-frontend-plugin#13]
The plugin does not check the AWS profile used by serverless at all. Can be set in --aws-profile CLI option or in serverless.yml provider.profile

Workaround for this is to run the deploy script as follows
```
AWS_PROFILE=<profile used here> serverless deploy
```

**Comment by mikkilevon** [comment]
Workaround for this is to run the deploy script as follows
```AWS_PROFILE=<profile used here> serverless deploy```

**Comment by rogersgt** [comment]
Thanks for the feedback! This should be resolved in `2.0.1`.
